### PR TITLE
Add "CAME" optimizer?

### PR DESCRIPTION
**Pull request by johnman3032**
A while ago I came across this new optimizer called "CAME": 
https://github.com/yangluo7/CAME
https://arxiv.org/abs/2307.02047
It uses less VRAM than AdamW but seems to retain quality unlike Adafactor. I have used it for a while and I think it could be a nice addition. Although the optimizer list starts to get a bit long. 

From my own experience it seems that adding "betas=0.9,0.999,0.9999 weight_decay=0.01" in "Optimizer extra arguments" is recommended, but not required. LR is said to be 3-1x smaller than AdamW. I would recommend going as low as 5-10x smaller than AdamW if one is not getting good results.

This is my first PR so I may not have done things efficiently.

### CODE REVIEW

**Comment by bmaltais** [comment]
This look like agreat PR but it need to be files against the kohya sd-scripts repo. Once kohya merge the PR in his code I will then pull it from there. Updating the files maintained by kohya outside his repo is calling for trouble in the future and will lead for issues with supporting new updates.

Please open a PR directly at: https://github.com/kohya-ss/sd-scripts

**Comment by FurkanGozukara** [comment]
I got the best sdxl results with adafactor. Tested all throughly

**Comment by johnman3032** [comment]
> I got the best sdxl results with adafactor. Tested all throughly

Even with AdamW? I too observed that CAME does not seem to work well with SDXL, but it does do better with SD1.5. I am not sure why, maybe it needs a different learning rate or the parameters need to be different.

**Comment by FurkanGozukara** [comment]
> AdamW

yes better than that. i did total over 120 full trainings . all for SDXL DreamBooth

**Pull request closed without merging**
