### PR TITLE
LoCon script auto upgrade feature

### PR DESCRIPTION
**Pull request by Ki-wimon**
I think the error occured is due to some bugs from the old version of LoCon scripts. So I make it able to do git pull automatically while pressing training button.

### CODE REVIEW

**Comment by Ki-wimon** [comment]
There are some changes of the cmd args to LoCon still not add in this pr. I'll make changes later.

**Comment by Ki-wimon** [comment]
I have done a series of changes and it should work now. I also change the steps and the minimum of the network rank and alpha gliders.

**Comment by bmaltais** [comment]
Merged. Will be doing some more testing. So far so good... Working fine now.

**Comment by bmaltais** [comment]
@Ki-wimon I have changed the GUI integration part. You may want to sync your local branch with the dev branch to pull them in. Review the new GUI layout and let me know what you think.

**Pull request merged**
