### PR TITLE
bring back SDXL Parameters accordion for dreambooth gui

### PR DESCRIPTION
**Pull request by b-fission**
The SDXL options panel has been missing in the dreambooth tab for a while. 
Fixed first part of issue #2542

### CODE REVIEW

**Comment by b-fission** [comment]
When `cache_text_encoder_outputs` is enabled, the training script will fail with a data type error. That error didn't happen in v24.1.4 ... it looks like v24.1.5 pulled in a dev branch of sd-scripts because I see SD3 related code in there.

**Comment by bmaltais** [comment]
Hi, wonder since when this has been missing. Did I somehow broke the code and removed SDXL support in Dreambooth?

**Comment by bmaltais** [comment]
> When `cache_text_encoder_outputs` is enabled, the training script will fail with a data type error. That error didn't happen in v24.1.4 ... it looks like v24.1.5 pulled in a dev branch of sd-scripts because I see SD3 related code in there.

Humm... Perhaps I commited the wrong sd-scripts branch in my last dev branch commit... LE me fix that...

**Comment by bmaltais** [comment]
Is it possible this has been missing all along? I must have forgotten to add it in there... not one complained about it missing ;-)

OK, I will merge the change as it appear to add missing parameters...

**Pull request merged**
