### PR TITLE
Remove bitsandbytes version to fix CUDA version 12x compatible problem

### PR DESCRIPTION
**Pull request by ArtificialCleverness**

### CODE REVIEW

**Comment by ArtificialCleverness** [comment]
It might help with following issues:
#465

**Comment by bmaltais** [comment]
Unfortunatly this change is causing issues with my setup... so for me using 0.35.0 is the key. The latest version cause traceback errors.

**Comment by bmaltais** [comment]
@ArtificialCleverness can you try to replace the bitsandbytes line with this and test if it still work for you:

```
bitsandbytes==0.35.0; sys_platform == 'win32'
bitsandbytes==0.38.1; (sys_platform == "darwin" or sys_platform == "linux")
```

**Comment by ArtificialCleverness** [comment]
I have done my testing on RTX4090 + cu121 + python3.10.11 + Ubuntu 22.04, it works fine for me. 
I will submit another PR and close this one.

**Pull request closed without merging**
