### PR TITLE
Update requirements_runpod.txt

### PR DESCRIPTION
**Pull request by btcrm**
modified the typo

### CODE REVIEW

**Comment by bmaltais** [comment]
Rebased to sd3-flux.1

No direct changes to master as sd3-flux.1 will soon be merged in dev then dev in master.

Not sure if this change is required given how much has changed in sd3-flux.1 branch...

**Comment by FurkanGozukara** [comment]
@bmaltais runpod requirements broken at the moment here logs

```
 ______                 ______            _
(_____ \               (_____ \          | |
 _____) ) _   _  ____   _____) )___    __| |
|  __  / | | | ||  _ \ |  ____// _ \  / _  |
| |  \ \ | |_| || | | || |    | |_| |( (_| |
|_|   |_||____/ |_| |_||_|     \___/  \____|

For detailed documentation and guides, please visit:
https://docs.runpod.io/ and https://blog.runpod.io/


root@6fd31d6e84f7:/workspace# chmod +x RunPod_Kohya_FLUX_Installer_part1.sh
./RunPod_Kohya_FLUX_Installer_part1.sh
Get:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease [1581 B]
Get:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  Packages [1071 kB]                                                                                 
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]                                                               
Get:4 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]                                                   
Get:5 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]                                     
Get:6 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [2377 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]      
Get:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [33.9 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]               
Get:10 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [3205 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1162 kB]    
Get:15 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [44.7 kB]  
Get:16 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]          
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1450 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [3283 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [51.8 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2654 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [81.4 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [33.7 kB]
Fetched 35.8 MB in 3s (12.6 MB/s)                             
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
117 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'python3-tk' instead of 'python3.10-tk'
The following additional packages will be installed:
  blt libtcl8.6 libtk8.6 libxft2 libxrender1 libxss1 tk8.6-blt2.5 tzdata x11-common
Suggested packages:
  blt-demo tcl8.6 tk8.6 tix python3-tk-dbg
The following NEW packages will be installed:
  blt libtcl8.6 libtk8.6 libxft2 libxrender1 libxss1 python3-tk tk8.6-blt2.5 tzdata x11-common
0 upgraded, 10 newly installed, 0 to remove and 117 not upgraded.
Need to get 2973 kB of archives.
After this operation, 14.1 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 tzdata all 2024a-0ubuntu0.22.04.1 [349 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libtcl8.6 amd64 8.6.12+dfsg-1build1 [990 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxrender1 amd64 1:0.9.10-1build4 [19.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxft2 amd64 2.3.4-1 [41.8 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 x11-common all 1:7.7+23ubuntu2 [23.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxss1 amd64 1:1.2.3-1build2 [8476 B]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libtk8.6 amd64 8.6.12-1build1 [784 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 tk8.6-blt2.5 amd64 2.5.3+dfsg-4.1build2 [643 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 blt amd64 2.5.3+dfsg-4.1build2 [4838 B]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 python3-tk amd64 3.10.8-1~22.04 [110 kB]
Fetched 2973 kB in 1s (5632 kB/s)     
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package tzdata.
(Reading database ... 20729 files and directories currently installed.)
Preparing to unpack .../0-tzdata_2024a-0ubuntu0.22.04.1_all.deb ...
Unpacking tzdata (2024a-0ubuntu0.22.04.1) ...
Selecting previously unselected package libtcl8.6:amd64.
Preparing to unpack .../1-libtcl8.6_8.6.12+dfsg-1build1_amd64.deb ...
Unpacking libtcl8.6:amd64 (8.6.12+dfsg-1build1) ...
Selecting previously unselected package libxrender1:amd64.
Preparing to unpack .../2-libxrender1_1%3a0.9.10-1build4_amd64.deb ...
Unpacking libxrender1:amd64 (1:0.9.10-1build4) ...
Selecting previously unselected package libxft2:amd64.
Preparing to unpack .../3-libxft2_2.3.4-1_amd64.deb ...
Unpacking libxft2:amd64 (2.3.4-1) ...
Selecting previously unselected package x11-common.
Preparing to unpack .../4-x11-common_1%3a7.7+23ubuntu2_all.deb ...
Unpacking x11-common (1:7.7+23ubuntu2) ...
Selecting previously unselected package libxss1:amd64.
Preparing to unpack .../5-libxss1_1%3a1.2.3-1build2_amd64.deb ...
Unpacking libxss1:amd64 (1:1.2.3-1build2) ...
Selecting previously unselected package libtk8.6:amd64.
Preparing to unpack .../6-libtk8.6_8.6.12-1build1_amd64.deb ...
Unpacking libtk8.6:amd64 (8.6.12-1build1) ...
Selecting previously unselected package tk8.6-blt2.5.
Preparing to unpack .../7-tk8.6-blt2.5_2.5.3+dfsg-4.1build2_amd64.deb ...
Unpacking tk8.6-blt2.5 (2.5.3+dfsg-4.1build2) ...
Selecting previously unselected package blt.
Preparing to unpack .../8-blt_2.5.3+dfsg-4.1build2_amd64.deb ...
Unpacking blt (2.5.3+dfsg-4.1build2) ...
Selecting previously unselected package python3-tk:amd64.
Preparing to unpack .../9-python3-tk_3.10.8-1~22.04_amd64.deb ...
Unpacking python3-tk:amd64 (3.10.8-1~22.04) ...
Setting up libxrender1:amd64 (1:0.9.10-1build4) ...
Setting up x11-common (1:7.7+23ubuntu2) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Setting up tzdata (2024a-0ubuntu0.22.04.1) ...

Current default time zone: 'Etc/UTC'
Local time is now:      Sun Oct 27 15:00:02 UTC 2024.
Universal Time is now:  Sun Oct 27 15:00:02 UTC 2024.
Run 'dpkg-reconfigure tzdata' if you wish to change it.

Setting up libtcl8.6:amd64 (8.6.12+dfsg-1build1) ...
Setting up libxss1:amd64 (1:1.2.3-1build2) ...
Setting up libxft2:amd64 (2.3.4-1) ...
Setting up libtk8.6:amd64 (8.6.12-1build1) ...
Setting up tk8.6-blt2.5 (2.5.3+dfsg-4.1build2) ...
Setting up blt (2.5.3+dfsg-4.1build2) ...
Setting up python3-tk:amd64 (3.10.8-1~22.04) ...
Processing triggers for libc-bin (2.35-0ubuntu3.4) ...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  psmisc
0 upgraded, 1 newly installed, 0 to remove and 117 not upgraded.
Need to get 119 kB of archives.
After this operation, 463 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 psmisc amd64 23.4-2build3 [119 kB]
Fetched 119 kB in 5s (25.1 kB/s) 
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package psmisc.
(Reading database ... 23060 files and directories currently installed.)
Preparing to unpack .../psmisc_23.4-2build3_amd64.deb ...
Unpacking psmisc (23.4-2build3) ...
Setting up psmisc (23.4-2build3) ...
Cloning into 'kohya_ss'...
remote: Enumerating objects: 14511, done.
remote: Counting objects: 100% (613/613), done.
remote: Compressing objects: 100% (268/268), done.
remote: Total 14511 (delta 396), reused 544 (delta 342), pack-reused 13898 (from 1)
Receiving objects: 100% (14511/14511), 22.79 MiB | 28.29 MiB/s, done.
Resolving deltas: 100% (10207/10207), done.
Branch 'sd3-flux.1' set up to track remote branch 'sd3-flux.1' from 'origin'.
Switched to a new branch 'sd3-flux.1'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'python3-tk' instead of 'python3.10-tk'
python3-tk is already the newest version (3.10.8-1~22.04).
0 upgraded, 0 newly installed, 0 to remove and 117 not upgraded.
Skipping git operations.
Ubuntu detected.
Python TK found...
Switching to virtual Python environment.
[10/27/24 15:00:30] INFO     Python version is 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]                                                                                                                              setup_common.py:28
[10/27/24 15:00:32] INFO     Submodule initialized and updated.                                                                                                                                                                setup_common.py:53
                    INFO     Installing python dependencies. This could take a few minutes as it downloads files.                                                                                                               setup_linux.py:14
                    INFO     If this operation ever runs too long, you can rerun this script in verbose mode to check.                                                                                                          setup_linux.py:15
                    INFO     Kohya_ss GUI version: v24.2.0                                                                                                                                                                    setup_common.py:371
                                                                                                                                                                                                                                                 
                    INFO     Installing/Validating requirements from requirements_runpod.txt...                                                                                                                               setup_common.py:161
[10/27/24 15:00:33] ERROR    Failed to install requirements: ERROR: Invalid requirement: 'tensorflow==2.14.0 wheel' (from line 8 of requirements_runpod.txt)                                                                  setup_common.py:188
                    INFO     Configuring accelerate...                                                                                                                                                                        setup_common.py:201
                    WARNING  Could not automatically configure accelerate. Please manually configure accelerate with the option in the menu or with: accelerate config.                                                       setup_common.py:274
Copying accelerate config file to: /root/.cache/huggingface/accelerate/default_config.yaml
Traceback (most recent call last):
  File "/workspace/kohya_ss/kohya_gui.py", line 6, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'
root@6fd31d6e84f7:/workspace# 
```

**Comment by FurkanGozukara** [comment]
@bmaltais this is urgently needed to fix sd3-flux.1 branch

**Comment by bmaltais** [comment]
Should be fixed

**Comment by bmaltais** [comment]
The refactoring of how requirements are installed has been a bit of a challenge. But now it will allow for running the same file format manually or via the setup.py.

I even added a new parameter to the GUI that allow you to specify a custom requirements file to use. Just add --requirements <file path> and it should use that during validation and install any missing custom modules.

**Comment by FurkanGozukara** [comment]
@bmaltais ty so much

I tested on RunPod and Massed Compute now works amazingly

**Pull request closed without merging**
