### PR TITLE
macOS GUI functionality, sub-processed GUI components

### PR DESCRIPTION
**Pull request by jstayco**
Creating a draft pull request for the moment since this is massive and you might want visibility on it before it's ready.

This is a massive WIP and should not be trusted or used right now. However, major milestones have been crossed. Both message boxes and file dialogs are now properly subprocessed and work on macOS. I think by extension, it may work on runpod environments as well, but that remains to be tested.

### CODE REVIEW

**Comment by bmaltais** [comment]
Interesting PR. I fiddled with the subprocess for Mac a little and gave up due to the massive amount of change required. Glad that someone was willing to take on that task.

Looking forward to the completed version. Hope those warnings can be dealt with... gradio can be super picky and a pain to deal with.

**Comment by jstayco** [comment]
It is a very large change set. At first I tried not to break or make huge changes, but that simply wasn't feasible with this one. So since I was breaking things anyway, I just started knocking things out. Hopefully, things will come out better in regards to general file handling. I'd also like to see easygui completely removed if I can do that since the vast majority of that is already gone since removing the msgboxes. Maybe we can even get a slightly smaller install afterwards.

**Comment by jstayco** [comment]
@bmaltais I have a check now for valid JSON files (placeholder function for now) is_valid_config() in common_gui.py. Is there a more appropriate spot for that, should I make a common_utilities.py file, or just keep it in common_gui?

**Comment by bmaltais** [comment]
> @bmaltais I have a check now for valid JSON files (placeholder function for now) is_valid_config() in common_gui.py. Is there a more appropriate spot for that, should I make a common_utilities.py file, or just keep it in common_gui?

I think it is best to keep it seperate. My original idea of the common_gui.py grew organically and is a bit of a mess at the moment ;-)

So I think keeping things is constructs where they belong will make support for the code easier. So please put it in common_utilities.py if you want.

**Comment by bmaltais** [comment]
I am really sorry. I wanten to fix the merge issues but ended-up merging into dev... This closed the draft PR you had created and there is no way to re-open it. Really sorry about that. But since it was a draft I reverted the merge.

**Comment by jstayco** [comment]
@bmaltais No problem. This is a huge one. It will probably take me some time. I'm having to refactor a whole lot and rewrite some parts. Would you prefer a new draft PR or I just keep the work on the side entirely until it's in a better place?

**Pull request merged**
