### PR TITLE
Add setup script for ubuntu users

### PR DESCRIPTION
**Pull request by devNegative-asm**
Creates a script which when run in Ubuntu, installs necessary dependencies and changes the accelerate commands to be compatible with bash.

Alternatively, lines 12-27 from ubuntu_setup.sh can be removed if this is put onto another branch where their changes to the source are visible (I recommend this).

### CODE REVIEW

**Comment by bmaltais** [comment]
Great stuff. DOes it run pretty well without modifications to the python code? I have not tested it myself... but if it does this is awesome!

**Comment by bmaltais** [comment]
I think deleting the .bat and .ps1 files will cause serious isssues with git pull commands. I suggest to keep them and simply add the .sh files to the repo... that way linux and windows users can use the same code base.

Can you update the PR with this change? I will merge it into the dev branch after.

**Comment by devNegative-asm** [comment]
When I tried, the commands as generated by python don't work on linux. I'll combine this with https://github.com/bmaltais/kohya_ss/pull/272 and update the PR.

**Comment by devNegative-asm** [comment]
I made as much of it work with ubuntu as I could test at the moment. It should in theory still work on windows, but I'm unable to test that.

**Comment by bmaltais** [comment]
Changes look good. I am doing a quick test and all appear to work so far. I will merge it to dev to test some more and then to master. Noce contribution! I am sure you will make many linus users happy.

**Pull request merged**
