### PR TITLE
20230629 add local model path

### PR DESCRIPTION
**Pull request by godlockin**
[steven] add path settings for local model, named by "model_dir" as we may download pre-trained model manually which can be loaded from local hardware

### CODE REVIEW

**Comment by bmaltais** [comment]
Hello @godlockin This look like a great PR... but some of it is changing sd-scripts files created and maintained by kohya_ss in his repo. I suggest this PR be changed to only keep the files pertinant to this repo and to open a PR for the sd-scripts files on the kohya_ss repo: https://github.com/kohya-ss/sd-scripts

Once he has merged the changes in his repo I will then be able to merge them in mine and then apply your modified PR on top.

Does it make sense?

**Comment by godlockin** [comment]
got it, i will create a pr to him then :)

**Comment by bmaltais** [comment]
I have been significantly reqorking the code into classes... I think this will require significant rework of the GUI code... but at least the new class approach make things easier... or at least should

**Comment by bmaltais** [comment]
I have debased the PR to the branch that include all the code structural change I did for SDXL

**Comment by godlockin** [comment]
yape, the base url isn't the "necessary" parameter for the normal pipeline, but maybe we can set as an variable load from ENV or by some other way to set it

as for the "normal" or "happy path" of the pipeline, some attributes/parameters may not need to set / customized in the GUI

**Pull request closed without merging**
