### PR TITLE
FIX: pip-24.x compatibility on GNU/Linux

### PR DESCRIPTION
**Pull request by kyeno**
pip-23.x and 24.x seem to have a problem with space-separated requirements.
Converting them back to `\n` does the trick.

### CODE REVIEW

**Comment by bmaltais** [comment]
This change will conflict with the sd3-flix.1 branch and future merge to dev then main...

Would you be ok if I rebase the PR to sd3-flux.1 and let you test it there? Knowing this will progress to main eventually when kohya progress his sd-scripts from sd3 to dev and then main?

**Comment by b-fission** [comment]
I use the gui primarily on Linux and this change seems likely to cause breakage on setup and package validation, especially for non-nvidia users.

The change might make sense (and it works?) if the user manually runs `pip install -r requirements_linux_xxx.txt` but that's not intended as I understand it.

As a sanity check, try running `./setup.sh --use-rocm` on the PR branch. Don't worry if you're not on a Radeon gpu, just observe. On my system, the gui will always fail to install torch+rocm due to the URL being line-breaked.

**Comment by kyeno** [comment]
Btw, same (or more) `setup.sh` errors with NVidia/default setup. I'll try something extra.

**Comment by kyeno** [comment]
Okay... I managed to get it working both with `setup.sh` and classic installation (`python3.10 -m venv venv`, `source venv/bin/activate`, `pip install --upgrade pip`, `pip install -r requirements_linux.txt`). I personally wouldn't call it a FIX, but rather a really nasty workaround that breaks the DRY standard, but... yeah.

I will post it here, in comments, as an example/point of discussion before actually doing any PR. This example only covers `requirements_linux.txt` for now, but I believe you could easily imagine how other files would look like. :)

```
$ cat requirements_linux.txt 
--extra-index-url https://download.pytorch.org/whl/cu118
torch==2.1.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
torchvision==0.16.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
xformers==0.0.23.post1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
bitsandbytes==0.43.0
tensorboard==2.15.2
tensorflow==2.15.0.post1
onnxruntime-gpu==1.17.1
-r requirements.txt
```

*Cough*

Do you want me to commit this atrocity (together with other `requirements_*` files) and simply call it a "workaround/hack"?

**Comment by bmaltais** [comment]
Humm... now that I look at the solution on my computer screen (vs mobile phone) I think it is not totally bad as it allow to specify on a per module basis which need the --extra-index-url option.

It certainly is not DRY... but would allow to install manually and with setup.sh from the same file.

The only thing that looks weird (probably due to how setup.sh work internally) is the 1st line with just "--extra-index-url https://download.pytorch.org/whl/cu118" on it...

**Comment by bmaltais** [comment]
OK... Look this is exactly how I have been approaching it for windows... I guess I never applied the "format" change to linux or mac because I don't really use those platforms and figured if no one complain about the current style then all should be good.

So perhaps converting all requirements files to use the "one per line" `torch==2.4.0+cu124 --extra-index-url https://download.pytorch.org/whl/cu124` would satisfy everyone?

**Comment by bmaltais** [comment]
Well... look like the syntax with the --index-url in the requirements file is not supported by pip nativelly... and this is a shame... because it is not possible to mix and match modules in the same requirements file for different --index-url...

So back to the design board... I think the 1st step is how can requirements be installed from a single requirements file for both modules that require --index-urn and ones that don't... Is it even possible? pip is such a restrictive module install tool.

**Comment by bmaltais** [comment]
I found this syntax might actually work... but I need to do more testing with it... It will for sure require some setup.py asdjustments if it properly install the requirements in one go...

```
# Custom index URL for specific packages
--extra-index-url https://download.pytorch.org/whl/cu124

torch==2.4.1
torchvision==0.19.1
xformers==0.0.28.post1

# Reset to the default index for other packages
--extra-index-url https://pypi.org/simple

bitsandbytes==0.44.0
tensorboard
tensorflow>=2.16.1
onnxruntime-gpu==1.17.1

-r requirements.txt
```

**Comment by bmaltais** [comment]
OK, I have pushed an update that should allow you to mimick how I tested the new syntax for Windows. I am sure you can update the required linux requirements files to make it do the same so it will work manually and via setup.py.

I have pushed the update in the sd3-flux.1 branch

**Comment by bmaltais** [comment]
I have attempted to fix the linux requirements... please have a look and test if I did a good job ;-)

**Comment by b-fission** [comment]
The updated linux requirements seem to work.
I've tested the installation process with pip and setup.sh for nvidia/rocm/ipex.

**Comment by bmaltais** [comment]
Glad it work for you. Let see if there are issues reported with the updated code. I did rebase this PR against the sd3-flux.1 branch. Not sure if it is still needed...

**Comment by b-fission** [comment]
Commits https://github.com/bmaltais/kohya_ss/commit/67f5f7b1566aa8e2bda75fc90aa98ed827ad27b1 broke the validation step. It looks like using `subprocess.run()` with an arg list and `shell=True` causes python to be called without the other arguments.

**Comment by bmaltais** [comment]
I did not test it under Linux... Will try to find what is causing this...

**Comment by FurkanGozukara** [comment]
@b-fission thanks for report i just had opened this issue https://github.com/bmaltais/kohya_ss/issues/2929

@bmaltais currently broken people already reporting what to do :)

**Comment by bmaltais** [comment]
Should be fixed with the latest commit.

**Comment by FurkanGozukara** [comment]
@bmaltais thank you so much appreciate your speed

currently runpod has issue :D https://github.com/bmaltais/kohya_ss/pull/2930#issuecomment-2440058891

**Comment by kyeno** [comment]
Hey! Awesome work guys. Sorry, I had to bail and didn't manage to get back to the computer until today.
Anyway, speaking of my non-DRY solution - after taking another look it seems that you have already implemented something very similar for Windows alone:

https://github.com/bmaltais/kohya_ss/blob/master/requirements_pytorch_windows.txt

Albeit without the initial line.

@bmaltais, that initial line though is still something compatible with `pip` standard, even though it looks rather nasty.

I also had another idea of implementing this that would require slightly modding the setup script.
It will introduce a bit of hardcodedness-logic, but... I'll see if I have a bit of time to try and write it up later today (likely during the evening).

That is - if it's still a game. I noticed you already did some stuff/solutions.

**Comment by bmaltais** [comment]
Yeah, I got carried away and implemented a solution so both manual and setup use the same files now... Without the custom pip requirements format. It the current solution work as you originally intended then you can close this PR. Otherwise I will close I try in a few days.

**Comment by potatoker** [comment]
on the newest flux branch, still get the same error 
、、
libcusparse.so.12: symbol __nvJitLinkComplete_12_4 version libnvJitLink.so.12 not defined in file            
                         libnvJitLink.so.12 with link time reference  
、、

**Comment by b-fission** [comment]
> on the newest flux branch, still get the same error on linux
> 
> > libcusparse.so.12: symbol __nvJitLinkComplete_12_4 version libnvJitLink.so.12 not defined in file libnvJitLink.so.12 with link time reference

Are you starting with a freshly created venv?

If not, it's possible that an older build of libnvJitLink is still there. Try reinstalling it with this command, then try again.
`./venv/bin/pip install --force-reinstall nvidia-nvjitlink-cu12==12.4.127`

**Pull request closed without merging**
