### PR TITLE
Fix VAE being applied (for LoRA training)

### LINKED ISSUE #1655: Loading external VAE does not work in LoRA training
Hi there, as described in the title trying to load a external VAE will do nothing in the LoRA tab (might happen too in Dreambooth?)
imagen

Printing the command does not show any references to the VAE, and starting training does not show it being loaded
imagen

Passing --vae "F:/stable-diff/stable-diffusion-webui/models/VAE/counterfeitV25VAE_v25.pt" as Additional Parameter works as expected.

imagen

### PR DESCRIPTION
**Pull request by rockerBOO**
There is an option for setting the VAE but it was not being send to the script. This should be adding the VAE to the script. Can confirm by the script that runs should have 

```
accelerate launch train_network.py ... --vae /path/to/vae.safetensors
```

And it should show in the output.

Fixes #1655

### CODE REVIEW

**Comment by bmaltais** [comment]
Hummm, I am not sure if this work. I see you are addinf the vae parameter to the functions... but there is no passing of that value in the caller. Is this really working? If so I don't quite understand how...

**Comment by bmaltais** [comment]
OK, I see that the VAE path is captured in class_advanced_training.py... but you are not passing it to the functions in the provided PR. Wait, ok, now I see it ;-) All good! Thank your for fixing this oversight! There are so many options that when refactoring code it can lead to ommision

**Comment by rockerBOO** [comment]
Ahh I should had explained that a little better. We we're doing VAE testing and found it to be very impactful for training. But someone discovered it wasn't being passed to the training script. So I worked it from the button down to the script and found it was missing being passed at the first step. 

Thanks for merging!  This will help a lot of people have better quality trainings with a fine tuned VAE.

**Comment by bmaltais** [comment]
Is there a VAE you recommend to try for training?

**Comment by rockerBOO** [comment]
<https://huggingface.co/stabilityai/sd-vae-ft-mse> or <https://huggingface.co/stabilityai/sd-vae-ft-ema> for SD 1.5.

Can see the comparisons on the model card. Says ft-ema has a slightly lower FID. ft-mse says smoother outputs from ft-ema version. Many people go with ft-mse version.

<https://huggingface.co/stabilityai/sdxl-vae> for SDXL.

Kohya supports putting in the path like `--vae="stabilityai/sdxl-vae"` which will download the VAE model.

**Pull request merged**
