### PR TITLE
Weights & biases UI options

### PR DESCRIPTION
**Pull request by x-CK-x**
I have added the option for the user to put the wandb api key in a textbox under the advanced configuration dropdown and a checkbox to toggle for using wandb logging.

### CODE REVIEW

**Comment by bmaltais** [comment]
Nice idea. I see you did not add the change to the textual_inversion_gui.py file. Is it because that trainer does not support the option?

**Comment by x-CK-x** [comment]
My apologies. I forgot it when uploading. Just added.

**Comment by bmaltais** [comment]
OK, before I merge, I wonder if you would feel OK to adapt the code to leverage the central common_gui.py implementation vs carrying the config gradio block in each trainer GUI. I know, it is almost as much work given the sprawling of variables in each any way... but if one needed to change the gradio elements in the future this allow to make the change in only one file vs 4.

Let me know if you can tackle this. Otherwise I might refactor the code to implement it using the common_gui.ps in the library folder in the future.

**Comment by x-CK-x** [comment]
Just went back and adapted it to the common gui implementation.

**Comment by bmaltais** [comment]
Awesome, will make updates more user freindly if ever needed in the future. I will merge to dev and let it soak until the next release.

**Pull request merged**
