### PR TITLE
Add setup/upgrade batch files

### PR DESCRIPTION
**Pull request by missionfloyd**
Greatly simplifies installation on Windows.

### CODE REVIEW

**Comment by jstayco** [comment]
@bmaltais I had planned on giving the PowerShell installation stuff and README section the same treatment as macOS once I wrapped up current efforts. I think PowerShell is the way to go for the vast majority of people, but batch files are still good for people in high security environments or where they don't have the ability to run PowerShell scripts at all.

@missionfloyd This looks nice! If you want to make it more portable you can grab the directory where the script lives like this
```
# This gets the script directory.
SET path=%~dp0

# This removes the trailing slash if needed.
echo %path:~0,-1%
```
then use `git -C %path% _____". Then you can fix all the paths referenced in your batch files to prepend that. That way you don't have to cd to the folder to use it. You could be in C:\Users\me\Desktop and run the command "C:\Users\me\Programs\kohya_ss\update.bat" for example and it would work fine because all of your paths are relative to the script and not the user.

**Comment by bmaltais** [comment]
Look ready to implement to me... do you want to add anything else?

**Comment by missionfloyd** [comment]
I think it's good to go.

**Comment by bmaltais** [comment]
Merging to dec for next release and testing. Many thanks

**Pull request merged**
