### PR TITLE
[major] upgrades / uplift (cuda, python, libs)

### PR DESCRIPTION
**Pull request by sammcj**
I managed to upgrade pretty much everything for Linux/Docker/macOS to their latest stable versions and Kohya (Docker on Linux) seems to be running great.

I thought I'd contribute back by offering a PR with the updates, however I completely understand if you don't wish to accept this PR and would rather perform the updates yourself, if that is the case feel free to reject and close the PR.

---

Major changes:

- NVIDIA Release 23.09
- Python 3.11.x
- Cuda 12.2
- Python packages all updated to latest stable

Minor:

- References to SDXL 0.9 updated to 1.0
- Dockerfile logic improved to reduce layer duplication
- Fix spelling mistakes

Added:

- en-GB localisation file (Standard / International English).
- Added cuda/bin to PATH

I've been running the container on my Linux server, Perhaps someone who runs Windows/Runpod etc... could test on those platforms if they're likely to be problematic?

### CODE REVIEW

**Comment by bmaltais** [comment]
Look like a great update. It does veer off kohya official requirements and could potentially cause issues for some… so I will merge it into a new branch to test before merging to the main dev2 development branch

**Comment by sammcj** [comment]
Great, yeah no pressure to merge it as I know it's a big change, I just thought no harm in giving it a go at least.

**Comment by bmaltais** [comment]
I think the biggest issue is that the current setup and run code will not upgrade torch cleanly… so this is a big issue. Upgrading torch used to cause some serious issues and the only clean upgrade path was to destroy the vent and reinstall everything from scratch… will see how this goes.

**Comment by bmaltais** [comment]
Actually, there are some good bits in your PR that I could merge directly in dev2... like the localization, typos fix, SDXL 1.0 instead of 0.9, etc.

I feel it might be best to split the PR into two... One for the requirements update that might not be easy to accept given it is moving things in a territory where kohya_ss code may no longer bu supported... and one for the other things that are more bening.

What do you think @sammcj ? Perhaps a new branch with the updated requirements could be maintained in the repo to properly test and figure impact on existing users?

Could you split the PR into two?

**Comment by sammcj** [comment]
Yeah no worries at all! I try to get to that tonight or tomorrow after work 😄

**Comment by sammcj** [comment]
Sorry that took a while, here's the spelling/linting/cleanup PR - https://github.com/bmaltais/kohya_ss/pull/1589

**Comment by ashleykleynhans** [comment]
I don't recommend bumping CUDA to 12.x on the main branch because hosting providers like RunPod don't have CUDA 12.x on all of their hosts and that will cause issues.

**Pull request closed without merging**
