### PR TITLE
LoCon support feature

### PR DESCRIPTION
**Pull request by Ki-wimon**
Feture of LoCon (KohakuBlueleaf/LoCon) support can be an idea for the gui. It changes the cmd args and to clone the LoCon script files when the user doesn't have one if train as a LoCon.

### CODE REVIEW

**Comment by Ki-wimon** [comment]
the Locon models trained is not sure whether it is able to run utilities in this gui or not, and probably not.

**Comment by bmaltais** [comment]
Interesting PR. I will try it and see how it look and work. As you said it will probably introduce some confusion if a user create a Locon KoRA using the UI and the utilities choke on it... Wonder what is best for the implementation

**Comment by Naegles** [comment]
I believe the LoCon repo supports using different ranks for the lora part and loco part. Would probably make sense to make that available in the gui as well

**Comment by bmaltais** [comment]
I wonder if creating a new tab called LoCon that would essentially be a the same as a Dreambooth LoRA but with the LoCon option set to true... That way the same code would be used and would present the user with a clear difference... Not sure how much work it would be to transform the lora_gui.py to behave like that...

Essentially the kohya_gui would call lora_gui.py passing it a Locon=true value for a new Locon tab... This should work.

Do you fell ok with modifying the PR to implement it like that?

**Comment by Ki-wimon** [comment]
That's great. Making a new Locon tab is a good way to tell the user that LoCon is different from general LoRA and also prevent the confusion to users that LoCon models cannot use the LoRA utilities.

**Comment by bmaltais** [comment]
I will merge the PR to a new branch and weave the new tab in it. By the way, I was talking to kohya_ss about the PR and he mentionned he will integrate LoCon in his main code since he already integrated it for convnet apparently. You should reach out to him to discuss how your work and his can be integrated. Perhaps he can leverage your network?

**Comment by bmaltais** [comment]
Hummm, when I try running the code I get:

```
Traceback (most recent call last):
  File "D:\kohya_ss\train_network.py", line 507, in <module>
    train(args)
  File "D:\kohya_ss\train_network.py", line 129, in train
    network = network_module.create_network(1.0, args.network_dim, args.network_alpha, vae, text_encoder, unet, **net_kwargs)
  File "D:\kohya_ss\LoCon\locon\locon_kohya.py", line 21, in create_network
    network = LoRANetwork(
  File "D:\kohya_ss\LoCon\locon\locon_kohya.py", line 119, in __init__
    self.unet_loras = create_modules(LoRANetwork.LORA_PREFIX_UNET, unet, LoRANetwork.UNET_TARGET_REPLACE_MODULE)
  File "D:\kohya_ss\LoCon\locon\locon_kohya.py", line 106, in create_modules
    lora = LoConModule(lora_name, child_module, self.multiplier, self.conv_lora_dim, self.conv_alpha)
  File "D:\kohya_ss\LoCon\locon\locon.py", line 26, in __init__
    self.lora_down = nn.Conv2d(in_dim, lora_dim, k_size, stride, padding, bias=False)
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 444, in __init__
    super(Conv2d, self).__init__(
  File "D:\kohya_ss\venv\lib\site-packages\torch\nn\modules\conv.py", line 131, in __init__
    self.weight = Parameter(torch.empty(
TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```

**Comment by bmaltais** [comment]
Since I merged to dev you will need to re-open the PR... should have tested before merging...

**Pull request merged**
