### PR TITLE
caption from filename

### PR DESCRIPTION
**Pull request by kainatquaderee**
a small script for getting caption from filename

### CODE REVIEW

**Comment by bmaltais** [comment]
Would it be possible to add argparse style arguments parsing to make the script more like a reuseable tool? This way users can more easily use it without having to modify the file that would be managed via git and potentially causing git pull issues down the road.

**Comment by bmaltais** [comment]
Would it be possible to add argparse style arguments parsing to make the script more like a reuseable tool? This way users can more easily use it without having to modify the file that would be managed via git and potentially causing git pull issues down the road.

**Comment by kainatquaderee** [comment]
sure we can make a config file to interact with it instead of using it directly

**Comment by bmaltais** [comment]
Humm, I am sorry. I guess my comment was not clear. It is best if you can transform your utility to be like the caption.py under the tools directory. If you look at it you will see it can take arguments from the user to specify the image folder, the file_pattern, etc, etc. This is how I envision your utility to be like to it can be used in a similar manner...

https://github.com/bmaltais/kohya_ss/blob/master/tools/caption.py

I am not sure adding it to the GUI will really be necessary as this is something you would run once on a folder full of image to create colocated caption files... not something you would need to run often.

**Comment by kainatquaderee** [comment]
sure

**Comment by kainatquaderee** [comment]
now i guess it can be commited

**Comment by bmaltais** [comment]
There is an anoying rebase conflict I would rather not have to deal with. I have manually copied the proposed tool in the dev branch. I will close this PR since I added the code manually in the repo.

**Pull request closed without merging**
