### PR TITLE
Add IPEX

### PR DESCRIPTION
**Pull request by Disty0**
Initial Intel ARC GPU support with IPEX on Linux / WSL.
This PR presents IPEX as CUDA.

Users needs to set these manually:
Mixed precision to BF16,
Attention to SDPA,
Optimizer to: AdamW (or any other non 8 bit one).

And use;
```
./setup.sh --use-ipex
```
```
./gui.sh --use-ipex
```

Screenshot from 2023-09-08 04-32-25

### CODE REVIEW

**Comment by bmaltais** [comment]
Hi, this look like a great PR... but I see that most of the changes are related to kohya_ss code from his repo. I conly copy his code into mine so I suggest you put a PR with his repo for all things related to his code and only keep the GUI portion with mine. His repo is at: https://github.com/kohya-ss/sd-scripts

**Comment by Disty0** [comment]
Opened a PR in sd-scripts: https://github.com/kohya-ss/sd-scripts/pull/825

I will remove non gui codes after main repo is ready since my fork already in use by some users.

**Comment by Disty0** [comment]
@bmaltais IPEX support merged to dev branch. I've removed the non GUI changes from this PR.

**Comment by bmaltais** [comment]
OK, let me check the PR again and merge now that all the changes are specific to the GUI!

**Comment by bmaltais** [comment]
Code has been merged into the dev2 branch for testing.

**Pull request merged**
